development:
  adapter: postgresql
  encoding: unicode
  database: rails_poker_development
  pool: 5
  username: postgres
  password:
  sslmode: disable
  
production:
  adapter: postgresql
  encoding: unicode
  database: rails_poker_production
  pool: 5
  username: postgres
  password: